//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextEditorUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextEditorUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string ASK_QUESTION_CAPTION {
            get {
                return ResourceManager.GetString("ASK_QUESTION_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save the changes on &quot;[FILENAME]&quot;? ähnelt.
        /// </summary>
        public static string ASK_QUESTION_SAVE_CHANGE {
            get {
                return ResourceManager.GetString("ASK_QUESTION_SAVE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Save As ähnelt.
        /// </summary>
        public static string CONFIRM_SAVE_AS_CAPTION {
            get {
                return ResourceManager.GetString("CONFIRM_SAVE_AS_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;[FILENAME]&quot; already exists. Overwrite it? ähnelt.
        /// </summary>
        public static string CONFIRM_SAVE_AS_MSG {
            get {
                return ResourceManager.GetString("CONFIRM_SAVE_AS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string ERROR_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a text file ähnelt.
        /// </summary>
        public static string FILE_OPEN_FILENAME {
            get {
                return ResourceManager.GetString("FILE_OPEN_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Files (*.txt)|*.txt ähnelt.
        /// </summary>
        public static string FILE_OPEN_FILTER {
            get {
                return ResourceManager.GetString("FILE_OPEN_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .txt ähnelt.
        /// </summary>
        public static string FILE_SAVE_AS_EXTENSION {
            get {
                return ResourceManager.GetString("FILE_SAVE_AS_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die * ähnelt.
        /// </summary>
        public static string FILE_SAVE_AS_FILENAME {
            get {
                return ResourceManager.GetString("FILE_SAVE_AS_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Files (*.txt)|*.txt ähnelt.
        /// </summary>
        public static string FILE_SAVE_AS_FILTER {
            get {
                return ResourceManager.GetString("FILE_SAVE_AS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string FONTDIALOG_CANCEL_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("FONTDIALOG_CANCEL_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font does not exist on this system. ähnelt.
        /// </summary>
        public static string FONTDIALOG_ERROR_FONT {
            get {
                return ResourceManager.GetString("FONTDIALOG_ERROR_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font size has to be a number with 1 to 3 digits. ähnelt.
        /// </summary>
        public static string FONTDIALOG_ERROR_FONTSIZE_PARSE {
            get {
                return ResourceManager.GetString("FONTDIALOG_ERROR_FONTSIZE_PARSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font size hast to be between 1 and 100. ähnelt.
        /// </summary>
        public static string FONTDIALOG_ERROR_FONTSIZE_VALUE {
            get {
                return ResourceManager.GetString("FONTDIALOG_ERROR_FONTSIZE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size: ähnelt.
        /// </summary>
        public static string FONTDIALOG_FONTSIZE_LABEL_TEXT {
            get {
                return ResourceManager.GetString("FONTDIALOG_FONTSIZE_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font: ähnelt.
        /// </summary>
        public static string FONTDIALOG_FONTTYPE_LABEL_TEXT {
            get {
                return ResourceManager.GetString("FONTDIALOG_FONTTYPE_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string FONTDIALOG_OK_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("FONTDIALOG_OK_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font ähnelt.
        /// </summary>
        public static string FONTDIALOG_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("FONTDIALOG_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        public static string MENU_FILE {
            get {
                return ResourceManager.GetString("MENU_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Exit ähnelt.
        /// </summary>
        public static string MENU_FILE_EXIT {
            get {
                return ResourceManager.GetString("MENU_FILE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New ähnelt.
        /// </summary>
        public static string MENU_FILE_NEW {
            get {
                return ResourceManager.GetString("MENU_FILE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Open... ähnelt.
        /// </summary>
        public static string MENU_FILE_OPEN {
            get {
                return ResourceManager.GetString("MENU_FILE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Save ähnelt.
        /// </summary>
        public static string MENU_FILE_SAVE {
            get {
                return ResourceManager.GetString("MENU_FILE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save _As... ähnelt.
        /// </summary>
        public static string MENU_FILE_SAVE_AS {
            get {
                return ResourceManager.GetString("MENU_FILE_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fo_rmat ähnelt.
        /// </summary>
        public static string MENU_FORMAT {
            get {
                return ResourceManager.GetString("MENU_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fo_nt... ähnelt.
        /// </summary>
        public static string MENU_FORMAT_FONT_TYPE {
            get {
                return ResourceManager.GetString("MENU_FORMAT_FONT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _View ähnelt.
        /// </summary>
        public static string MENU_VIEW {
            get {
                return ResourceManager.GetString("MENU_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Status Bar ähnelt.
        /// </summary>
        public static string MENU_VIEW_STATUSBAR {
            get {
                return ResourceManager.GetString("MENU_VIEW_STATUSBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column ähnelt.
        /// </summary>
        public static string STATUS_BAR_POSITION_COLUMN {
            get {
                return ResourceManager.GetString("STATUS_BAR_POSITION_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line ähnelt.
        /// </summary>
        public static string STATUS_BAR_POSITION_LINE {
            get {
                return ResourceManager.GetString("STATUS_BAR_POSITION_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die , ähnelt.
        /// </summary>
        public static string STATUS_BAR_POSITION_SEPARATOR {
            get {
                return ResourceManager.GetString("STATUS_BAR_POSITION_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string TITLE_UNKNOWN {
            get {
                return ResourceManager.GetString("TITLE_UNKNOWN", resourceCulture);
            }
        }
    }
}
